accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
    mnemonic: "invite velvet shuffle day shed ramp page business index curve voice question crunch fence pepper olive honey train volcano crime very oil saddle average"
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
  port: 4501
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"
genesis:
  chain_id: orbit-1
  app_state:
    monitoringp:
      params:
        debugMode: true
#        consumerChainID: "spn-1"
#        consumerConsensusState:
#          root:
#            hash: "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="
#          timestamp: "2022-01-26T07:26:55.278516Z"
#          nextValidatorsHash: "E032B4650A751DB77A950AA6D7AB4EC92ACEABCEFB18D694F71DF5F07171C447"