accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
    mnemonic: "invite velvet shuffle day shed ramp page business index curve voice question crunch fence pepper olive honey train volcano crime very oil saddle average"
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
  port: 4501
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"
genesis:
  chain_id: orbit-1