accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
    mnemonic: "invite velvet shuffle day shed ramp page business index curve voice question crunch fence pepper olive honey train volcano crime very oil saddle average"
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
  port: 4501
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"
genesis:
  chain_id: orbit-1
  app_state:
    monitoringp:
      params:
        lastBlockHeight: 100
        consumerChainID: "spn-1"
        consumerConsensusState:
          root:
            hash: "47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="
          timestamp: "2022-02-06T11:05:28.620548Z"
          nextValidatorsHash: "FACAE113E5CB1565350646782D04197991DC04C8B096CAE17F56FB169A303EF1"